### ISSUE TITLE
好きなdiv要素に好きなフォントで文字を表示できるようにカスタマイズできますか？

### ISSUE THREAD

**Issue by linkevery2s** [code4fukui/egadv#1]
新しいアプリにノベルゲームを使いたいなと思い、こちらのAPIをお借りしたいと思っています。

・テキストをcssからフォント指定したい。

・ドラクエ風に吹き出し要素をdivで作り、そこに会話文として文字を入れていきたい。

と思っているのですが、カスタマイズ可能でしょうか？

ご検討のほど、よろしくお願いいたします。

**Comment by taisukef** [comment]
ありがとうございます！大歓迎です！

.textScreen のCSSを変更すればいけそうですね
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/1715217/205431930-d09f289c-c31b-4530-bffb-b687e0e9f28e.png">

**Comment by taisukef** [comment]
こんな感じでどうでしょう？

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/1715217/205432014-c61558b9-caef-452e-be41-9807e9c47628.png">

<script type="module">
import { bg, show } from "https://js.sabae.cc/egadv.js";
await bg();
await show("ここはどこでしょう?");
</script>
<style>
.textScreen {
  font-family: serif;
  margin: 60vh 1em 1em 1em;
  border: 4px solid white;
  background-color: black;
}
</style>

**Comment by linkevery2s** [comment]
おお！ありがとうございます！

そうです、そうです！イメージ通りです！

防災ノベルゲームの開発に使用させていただきます！

![スクリーンショット 2022-12-03 18 13 20](https://user-images.githubusercontent.com/23306970/205433564-b89fdac4-5f83-424d-9c87-404a34fc619b.png)

**Comment by taisukef** [comment]
おお、いい感じの画面ですね！
よかったです。楽しみにしていますっ
